import { StyleSheet } from 'react-native';
import { type Palette, TYPO, SPACE, RADIUS, TOUCH, typeStyle } from '../../lib/theme';

export const makeStyles = (P: Palette) => StyleSheet.create({
  root: { flex: 1 },
  fill: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 8 },
  header: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  title: { fontSize: 26, fontWeight: '800', color: P.ink },
  subtitle: { fontSize: 14, color: P.muted, marginTop: 2 },
  iconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: P.surface2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBtnText: { fontSize: 20 },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  // ── side drawer menu ──
  menuOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    flexDirection: 'row',
  },
  menuBackdrop: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: P.overlay,
  },
  menuPanel: {
    width: 300,
    maxWidth: '85%',
    backgroundColor: P.paper,
    paddingTop: 56,
    paddingHorizontal: 0,
    paddingBottom: 24,
    borderTopRightRadius: 0,
    borderBottomRightRadius: 0,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 12,
  },
  menuProfile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: P.surface2,
    marginBottom: 8,
  },
  menuAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: P.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuAvatarText: { fontSize: 22, fontWeight: '800', color: '#fff' },
  menuScroll: { flex: 1 }, // the whole drawer scrolls — less clutter, less pressure
  menuProfileInfo: { flex: 1 },  menuEmail: { fontSize: 17, fontWeight: '700', color: P.ink },
  menuEmailSub: { fontSize: 13, color: P.faint2, marginTop: 2 },
  menuBadge: { fontSize: 12, color: P.muted, marginTop: 3 },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
  },
  // ── chat history (in-drawer) ──
  histSection: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: P.surface2,
    paddingTop: 10,
  },
  newChatBtn: {
    marginHorizontal: 20,
    marginBottom: 10,
    backgroundColor: P.ink,
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
  },
  newChatBtnText: { color: P.paper, fontSize: 15, fontWeight: '700' },
  histTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: P.accentDeep,
    paddingHorizontal: 20,
    marginBottom: 6,
  },
  histList: { paddingHorizontal: 20, marginBottom: 4 },
  showMoreBtn: {
    marginHorizontal: 20,
    marginBottom: 8,
    backgroundColor: P.surface2,
    borderRadius: 10,
    paddingVertical: 9,
    alignItems: 'center',
  },
  showMoreText: { fontSize: 14, fontWeight: '700', color: P.accentDeep },
  histRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: P.surface,
    borderRadius: 10,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: P.border,
  },
  histMain: { flex: 1, paddingVertical: 9, paddingHorizontal: 12 },
  histRowTitle: { fontSize: 14, fontWeight: '600', color: P.ink },
  histTtl: { fontSize: 11, color: P.accent, marginTop: 2, fontWeight: '600' },
  histDel: { paddingHorizontal: 12, paddingVertical: 9 },
  histDelText: { fontSize: 14, color: P.faint3 },
  histEmpty: { fontSize: 13, color: P.faint3, paddingVertical: 8 },
  histHint: { fontSize: 11, color: P.faint3, paddingHorizontal: 20, marginBottom: 10 },
  menuItemIcon: { fontSize: 20, width: 28, textAlign: 'center' },
  menuItemText: { fontSize: 16, fontWeight: '600', color: P.ink, flex: 1 },
  menuSoon: {
    fontSize: 11,
    fontWeight: '700',
    color: P.accent,
    backgroundColor: P.tint,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 10,
  },
  menuLogout: { marginTop: 8, borderTopWidth: 1, borderTopColor: P.surface2 },
  menuLogoutText: { color: P.danger },
  // ── profile screen (WhatsApp/iOS-Settings pattern) ──
  // identity block: 64 avatar · 20/700 name · 13 gray email
  profileCard: { alignItems: 'stretch', maxHeight: '86%' },
  profileScroll: { flexGrow: 0 },
  profileHeader: { alignItems: 'center', paddingTop: 4, paddingBottom: 16 },
  profileAvatar: {
    width: 64, height: 64, borderRadius: 32,
    backgroundColor: P.accent, alignItems: 'center', justifyContent: 'center',
    marginBottom: 10,
  },
  profileAvatarText: { fontSize: 26, fontWeight: '800', color: '#fff' },
  profileName: { fontSize: 20, fontWeight: '700', color: P.ink, textAlign: 'center' },
  profileEmail: { fontSize: 13, color: P.muted, marginTop: 3, textAlign: 'center' },
  profileBadge: { fontSize: 12, color: P.muted, marginTop: 6 },
  // section headers: 13/600 gray (uppercase in EN only — Arabic has no case)
  sectionHeader: {
    fontSize: 13, fontWeight: '600', color: P.muted,
    marginTop: 18, marginBottom: 8, paddingHorizontal: 4,
  },
  // info card: grouped rows, 48 min height, 1px inset dividers
  infoCard: {
    backgroundColor: P.surface,
    borderRadius: 14,
    paddingHorizontal: 16,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 48,
    paddingVertical: 8,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: P.border,
  },
  infoRowLast: { borderBottomWidth: 0 },
  infoLabel: { fontSize: 15, color: P.muted, flexShrink: 0 },
  infoValue: { fontSize: 15, fontWeight: '600', color: P.ink, flex: 1, textAlign: 'right' },
  // filled inputs (M3/Revolut dominant pattern — never mix with outlined):
  // no border, radius 14, min-height 52, 16px text (iOS zooms below 16)
  fieldInput: {
    backgroundColor: P.input,
    borderRadius: 14,
    minHeight: 52,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: P.ink,
  },
  fieldHint: { fontSize: 12, color: P.muted, marginBottom: 8, lineHeight: 17, paddingHorizontal: 4 },
  fieldError: { fontSize: 12, color: P.danger, marginTop: 6, paddingHorizontal: 4 },
  fieldOk: { fontSize: 12, color: P.success, marginTop: 6, paddingHorizontal: 4 },
  // primary button: full-width, 52, 16/700 — thumb-zone save pattern
  primaryBtn: {
    backgroundColor: P.accent,
    borderRadius: 14,
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  primaryBtnDisabled: { opacity: 0.6 },
  primaryBtnText: { fontSize: 16, fontWeight: '700', color: '#fff' },
  ghostBtn: {
    borderRadius: 14,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  ghostBtnText: { fontSize: 15, fontWeight: '600', color: P.muted },
  // ── 👻 ghost key styles: deliberately plain, no trace ──
  secretGhostRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
  ghostBtnSmall: {
    borderRadius: 12,
    minHeight: 40,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: P.surface2,
  },
  ghostBtnSmallText: { fontSize: 13, fontWeight: '600', color: P.muted },
  secretSubForm: { marginTop: 8, paddingTop: 10, borderTopWidth: 1, borderTopColor: P.border },
  mgmtRow: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: P.border },
  mgmtRowHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 8 },
  mgmtRowTitle: { fontSize: 15, fontWeight: '700', color: P.ink, flex: 1 },
  mgmtRowActions: { flexDirection: 'row', gap: 6 },
  mgmtInline: { marginTop: 8, gap: 8 },
  demoPanel: {
    marginHorizontal: 16,
    marginBottom: 8,
    padding: 12,
    backgroundColor: P.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: P.borderWarn,
  },
  demoTitle: { fontSize: 13, fontWeight: '700', color: P.warn, marginBottom: 8 },
  demoRow: { flexDirection: 'row', gap: 8 },
  demoAction: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: P.accent,
  },
  demoDanger: { backgroundColor: P.gray },
  demoActionText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  tabs: { flexDirection: 'row', paddingHorizontal: 16, gap: 8, marginBottom: 8 },
  tab: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 22,
    backgroundColor: P.surface2,
  },
  // custom tabs: horizontal scrollable bar
  tabBar: { marginBottom: 8, maxHeight: 48 },
  tabBarInner: { paddingHorizontal: 16, gap: 8, alignItems: 'center' },
  tabAdd: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: P.surface2,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: P.border,
    borderStyle: 'dashed',
  },
  tabAddText: { fontSize: 18, color: P.text2, fontWeight: '700' },
  tabMenu: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  tabMenuBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: P.surface2,
  },
  tabMenuDel: { backgroundColor: P.dangerSoft },
  tabMenuText: { fontSize: 13, fontWeight: '700', color: P.text2 },
  iconRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'center',
    marginBottom: 12,
  },
  iconPick: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: P.input,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconPickActive: { backgroundColor: P.ink },
  iconPickText: { fontSize: 20 },
  fileRow: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: P.input,
    marginBottom: 6,
  },
  fileRowText: { fontSize: 15, fontWeight: '600', color: P.ink2 },
  tabActive: { backgroundColor: P.ink },
  tabText: { ...typeStyle(TYPO.subBold), color: P.text2 },
  tabTextActive: { color: P.paper },
  // chat
  chatList: { paddingHorizontal: 16, paddingVertical: 8, gap: 10, flexGrow: 1 },
  emptyChat: {
    alignItems: 'center',
    paddingTop: 56,
    paddingBottom: 24,
    paddingHorizontal: 24,
    gap: 10,
  },
  emptyIcon: { fontSize: 60 },
  emptyTitle: { ...typeStyle(TYPO.title), color: P.ink, textAlign: 'center' },
  emptySub: { ...typeStyle(TYPO.body), color: P.text2, textAlign: 'center' },
  // first-use teacher: tappable example cards
  tryLabel: { ...typeStyle(TYPO.subBold), color: P.muted, marginTop: SPACE.sm },
  exampleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACE.md,
    width: '100%',
    minHeight: 58,
    backgroundColor: P.surface,
    borderWidth: 1.5,
    borderColor: P.border,
    borderRadius: RADIUS.lg,
    paddingHorizontal: SPACE.lg,
    paddingVertical: SPACE.md,
    marginTop: SPACE.xs,
  },
  exampleIcon: { fontSize: 22 },
  exampleText: { flex: 1, ...typeStyle(TYPO.bodyBold), color: P.ink },
  exampleGo: { fontSize: 26, color: P.faint, fontWeight: '700' },
  pressed: { opacity: 0.55 },
  micHint: { ...typeStyle(TYPO.caption), color: P.faint, textAlign: 'center', marginTop: 2 },
  bubble: {
    borderRadius: 16,
    padding: 10,
    gap: 6,
  },
  bubbleUser: {
    backgroundColor: P.info,
    borderBottomRightRadius: 4,
  },
  bubbleApp: {
    backgroundColor: P.bubbleApp,
    borderBottomLeftRadius: 4,
  },
  // chat message wrapper: owns width + side alignment (bubble no longer does)
  msgWrap: { maxWidth: '85%', marginBottom: 2 },
  msgWrapUser: { alignSelf: 'flex-end', alignItems: 'flex-end' },
  msgWrapApp: { alignSelf: 'flex-start', alignItems: 'flex-start' },
  // long-press reaction bar (WhatsApp-style)
  reactBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: P.surface,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: P.border,
    paddingHorizontal: 8,
    paddingVertical: 4,
    gap: 4,
    marginBottom: 4,
  },
  reactHit: { borderRadius: 999, padding: 4 },
  reactHitOn: { backgroundColor: P.tint },
  reactEmoji: { fontSize: 22 },
  // chosen reaction badge pinned to the bubble corner
  reactionBadge: {
    position: 'absolute',
    bottom: -10,
    backgroundColor: P.surface,
    borderColor: P.border,
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 5,
    paddingVertical: 1,
  },
  reactionBadgeUser: { right: 8 },
  reactionBadgeApp: { left: 8 },
  reactionBadgeText: { fontSize: 13 },
  bubbleText: { ...typeStyle(TYPO.sub), color: P.ink },
  feedbackRow: { flexDirection: 'row', gap: 14, marginTop: 8, opacity: 0.9 },
  feedbackBtn: { fontSize: 14, opacity: 0.35 },
  feedbackBtnOn: { opacity: 1 },
  bubbleTextUser: { color: P.paper },
  bubbleSpinner: { marginTop: 4 },
  bubblePhoto: { width: 180, height: 135, borderRadius: 10, marginBottom: 6 },
  cardPhoto: { width: 120, height: 90, borderRadius: 10, backgroundColor: P.surface2 },
  // chat photo attach (photograph, then talk/write about it)
  photoPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: P.surface,
    borderRadius: 14,
    padding: 8,
    borderWidth: 1,
    borderColor: P.border,
  },
  photoPreviewImg: { width: 56, height: 56, borderRadius: 10, backgroundColor: P.surface2 },
  photoPreviewX: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: P.surface2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoPreviewXText: { fontSize: 14, color: P.text2, fontWeight: '700' },
  photoPreviewLabel: { fontSize: 13, color: P.muted, flex: 1 },
  chatFooter: { paddingHorizontal: 16, paddingBottom: 20, paddingTop: 8, gap: 8 },
  inputRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  composerBox: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: P.surface,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: P.border,
    paddingHorizontal: 4,
    paddingVertical: 4,
    minHeight: 44,
    maxHeight: 132,
  },
  cameraBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cameraBtnText: { fontSize: 19 },
  composerInput: {
    flex: 1,
    fontSize: 15,
    color: P.ink,
    paddingHorizontal: 4,
    paddingVertical: 6,
    maxHeight: 120,
  },
  micBtn: {
    width: TOUCH,
    height: TOUCH,
    borderRadius: TOUCH / 2,
    backgroundColor: P.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  micBtnRecording: { backgroundColor: P.danger },
  micBtnDisabled: { opacity: 0.5 },
  micBtnText: { fontSize: 22 },
  chatInput: {
    flex: 1,
    backgroundColor: P.input,
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 16,
    fontSize: 15,
    color: P.ink,
    borderWidth: 1,
    borderColor: P.border,
  },
  sendBtn: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: P.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnText: { color: '#fff', fontSize: 20, fontWeight: '800' },
  timer: { fontSize: 14, fontWeight: '700', color: P.accent, textAlign: 'center' },
  recRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, marginTop: 6 },
  // space browsing
  segRow: { flexDirection: 'row', paddingHorizontal: 16, gap: 6, marginBottom: 8 },
  seg: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 14,
    backgroundColor: P.surface2,
    alignItems: 'center',
  },
  segActive: { backgroundColor: P.info },
  segText: { fontSize: 13, fontWeight: '700', color: P.text2 },
  segTextActive: { color: P.paper },
  addRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  famRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: P.surface,
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  // ── directed shopping lists ──
  sectionTitle: { fontSize: 15, fontWeight: '800', color: P.ink, marginBottom: 8 },
  shopListsWrap: { paddingHorizontal: 16, marginBottom: 12 },
  shopListCard: {
    backgroundColor: P.surface,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: P.border,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  shopListHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  shopListTitle: { fontSize: 16, fontWeight: '800', color: P.ink, flex: 1 },
  shopListDel: { fontSize: 16, color: P.faint, padding: 4 },
  shopListAssignee: { fontSize: 13, color: P.info, fontWeight: '700', marginTop: 4 },
  shopListProg: { fontSize: 13, color: P.text3, marginTop: 4, fontWeight: '700' },
  startShopBtn: {
    marginTop: 10,
    backgroundColor: P.success,
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  startShopText: { color: P.paper, fontSize: 15, fontWeight: '800' },
  shopModalCard: { maxWidth: 420, alignItems: 'stretch', maxHeight: '85%' },
  shopModalHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  shopModalHeadBtns: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  shopShareBtn: { fontSize: 14, fontWeight: '700', color: P.accent },
  shopModalList: { fontSize: 16, fontWeight: '800', color: P.ink, marginTop: 2 },
  shopProgWrap: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 10, marginBottom: 6 },
  shopProgBar: { flex: 1, height: 10, borderRadius: 6, backgroundColor: P.border, overflow: 'hidden' },
  shopProgFill: { height: '100%', backgroundColor: P.success, borderRadius: 6 },
  shopProgText: { fontSize: 14, fontWeight: '800', color: P.ink },
  shopModalList2: { marginTop: 6, maxHeight: 380 },
  shopBigRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: P.surface,
    borderRadius: 14,
    padding: 16,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: P.border,
  },
  shopBigRowDone: { backgroundColor: P.successSoft, borderColor: P.borderSuccess },
  shopBigCheck: { fontSize: 26 },
  shopBigTitle: { fontSize: 18, fontWeight: '700', color: P.ink, flex: 1 },
  shopDoneBanner: {
    fontSize: 15,
    fontWeight: '800',
    color: P.success,
    textAlign: 'center',
    marginTop: 6,
  },
  shopDoneBtn: { marginTop: 12, alignSelf: 'center', minWidth: 160 },
  assigneeChip: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: P.infoSoft,
  },
  assigneeText: { fontSize: 12, fontWeight: '700', color: P.info },
  assignBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: P.surface2,
  },
  assignBtnText: { fontSize: 12, fontWeight: '700', color: P.text2 },
  moreSpinner: {
    marginVertical: 12,
    alignSelf: 'center',
  },
  searchItems: {
    backgroundColor: P.surface,
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: P.borderWarn,
  },
  searchItemsLabel: { fontSize: 13, fontWeight: '700', color: P.warn, marginBottom: 6 },
  searchItemRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 6 },
  list: { paddingHorizontal: 16, paddingBottom: 16, gap: 10 },
  card: {
    backgroundColor: P.surface,
    borderRadius: 14,
    padding: 14,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  cardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  moveBtn: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: P.surface2,
  },
  moveBtnText: { fontSize: 12, fontWeight: '700', color: P.text2 },
  cardTopActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  playBtn: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: P.info,
  },
  playBtnText: { fontSize: 12, fontWeight: '700', color: P.paper },
  thingThumb: { width: 56, height: 56, borderRadius: 10, backgroundColor: P.surface2 },
  photoBtn: { padding: 6 },
  photoBtnText: { fontSize: 22 },
  viewerBg: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.92)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  viewerImg: { width: '100%', height: '80%' },
  viewerHint: { color: '#fff', marginTop: 12, fontSize: 14 },
  moveRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginVertical: 8,
    padding: 8,
    backgroundColor: P.paper,
    borderRadius: 10,
  },
  moveLabel: { fontSize: 13, fontWeight: '700', color: P.text2 },
  moveTarget: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: P.ink,
  },
  moveTargetText: { fontSize: 13, fontWeight: '700', color: P.paper },
  sugBtns: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  cardText: { fontSize: 15, color: P.ink, lineHeight: 22 },
  cardMeta: { fontSize: 12, color: P.faint },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: P.border,
  },
  itemIcon: { fontSize: 15, marginTop: 1 },
  itemBody: { flex: 1 },
  itemTitle: { fontSize: 14, fontWeight: '600', color: P.ink, lineHeight: 20 },
  itemDetails: { fontSize: 13, color: P.muted, marginTop: 2 },
  itemDone: { textDecorationLine: 'line-through', color: P.faint },
  itemDue: { fontSize: 12, color: P.accent, marginTop: 2 },
  // ── borrowing (مين أخذها؟) ──
  borrowBadge: { fontSize: 13, color: P.warn, marginTop: 2, fontWeight: '600' },
  returnBtn: { fontSize: 13, color: P.success, marginTop: 2 },
  returnBtnConfirm: { color: P.danger, fontWeight: 'bold' },
  muted: { fontSize: 13, color: P.faint },

  // ── auth + invites ──
  upgradeBanner: {
    backgroundColor: P.surface,
    borderBottomWidth: 1,
    borderBottomColor: P.border,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  upgradeText: { fontSize: 13, fontWeight: '600', color: P.warn, marginBottom: 8 },
  upgradeRow: { flexDirection: 'row', gap: 8 },
  upgradeInput: {
    flex: 1,
    backgroundColor: P.input,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    fontSize: 14,
    color: P.ink,
    borderWidth: 1,
    borderColor: P.border,
  },
  upgradeBtn: {
    backgroundColor: P.ink,
    borderRadius: 10,
    paddingHorizontal: 18,
    justifyContent: 'center',
  },
  upgradeBtnText: { color: P.paper, fontSize: 14, fontWeight: '700' },
  upgradeErr: { color: P.danger, fontSize: 13, marginTop: 6 },
  famHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 4,
    paddingBottom: 8,
  },
  famMembers: { fontSize: 14, color: P.text3, fontWeight: '600' },
  // ── multi-family switcher ──
  famSwitchText: { fontSize: 17, fontWeight: '700', color: P.ink },
  famTitleBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    paddingEnd: 4,
  },
  famEditBtn: {
    minWidth: 44,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  famEditBtnText: { fontSize: 16 },
  famSwitchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: P.surface,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 8,
    gap: 10,
  },
  famSwitchRowActive: { borderWidth: 1.5, borderColor: P.accent },
  famSwitchRowMain: { flex: 1, minHeight: 44, justifyContent: 'center' },
  famSwitchRowName: { fontSize: 16, fontWeight: '700', color: P.ink },
  famSwitchRowSub: { fontSize: 12, color: P.muted, marginTop: 2 },
  famActionBtn: {
    minWidth: 76,
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: P.surface2,
    paddingHorizontal: 12,
  },
  famActionBtnArmed: { backgroundColor: P.danger },
  famRowLocked: {
    fontSize: 12,
    fontWeight: '600',
    color: P.muted,
    paddingHorizontal: 12,
    minHeight: 44,
    textAlignVertical: 'center',
  },
  famActionText: { fontSize: 14, fontWeight: '700', color: P.danger },
  famActionTextArmed: { color: '#fff' },
  joinCodeInput: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: 4,
    marginBottom: 4,
  },
  famLink: { padding: 4 },
  famLinkText: { fontSize: 13, color: P.accent, fontWeight: '600' },
  inviteBtn: {
    backgroundColor: P.ink,
    borderRadius: 12,
    paddingVertical: 7,
    paddingHorizontal: 14,
  },
  inviteBtnText: { color: P.paper, fontSize: 13, fontWeight: '700' },
  inviteBtnFull: {
    backgroundColor: P.ink,
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    marginBottom: 14,
  },
  membersWrap: { paddingHorizontal: 16, paddingTop: 10 },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: P.surface,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: P.border,
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: P.tint,
    alignItems: 'center',
    justifyContent: 'center',
    marginEnd: 10,
  },
  memberAvatarText: { fontSize: 17, fontWeight: '700', color: P.accent },
  memberInfo: { flex: 1 },
  memberEmail: { fontSize: 14, fontWeight: '600', color: P.ink },
  memberEmailSub: { fontSize: 11, color: P.faint2, marginTop: 1 },
  memberRole: { fontSize: 12, color: P.text3, marginTop: 2 },
  removeBtn: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: P.surface,
  },
  removeBtnConfirm: { backgroundColor: P.danger },
  removeBtnText: { fontSize: 13, fontWeight: '700', color: P.danger },
  removeBtnTextConfirm: { color: P.paper },
  famLinkCenter: { alignItems: 'center', paddingVertical: 10 },
  leaveBtn: {
    marginTop: 6,
    borderRadius: 12,
    paddingVertical: 11,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: P.borderWarn,
    backgroundColor: P.surface,
  },
  leaveBtnConfirm: { backgroundColor: P.danger, borderColor: P.danger },
  leaveBtnText: { fontSize: 14, fontWeight: '700', color: P.danger },
  leaveBtnTextConfirm: { color: P.paper },
  modalBg: {
    flex: 1,
    backgroundColor: P.overlay,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  modalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: P.paper,
    borderRadius: 18,
    padding: 22,
    alignItems: 'center',
  },
  modalTitle: { fontSize: 19, fontWeight: '800', color: P.ink, marginBottom: 10 },
  modalBody: { fontSize: 14, color: P.text3, textAlign: 'center', lineHeight: 21, marginBottom: 14 },
  // trash rows
  trashRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: P.surface,
    borderRadius: 12,
    padding: 10,
    marginBottom: 8,
  },
  trashMain: { flex: 1 },
  trashTitle: { fontSize: 14, fontWeight: '700', color: P.ink },
  trashMeta: { fontSize: 12, color: P.faint, marginTop: 3 },
  trashActions: { flexDirection: 'row', alignItems: 'center' },
  trashBtn: { paddingHorizontal: 10, paddingVertical: 8 },
  // trash filter chips
  trashFilters: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
    marginBottom: 12,
  },
  trashChip: {
    backgroundColor: P.surface,
    borderWidth: 1,
    borderColor: P.border,
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  trashChipOn: { backgroundColor: P.ink, borderColor: P.ink },
  trashChipText: { fontSize: 13, fontWeight: '600', color: P.ink },
  trashChipTextOn: { color: P.paper },
  // secret vault full page
  vaultPage: { flex: 1, backgroundColor: P.paper },
  // trash full page
  trashPage: { flex: 1, backgroundColor: P.paper },
  trashPageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: P.border,
  },
  trashPageTitleWrap: { flex: 1, alignItems: 'center' },
  trashPageTitle: { fontSize: 17, fontWeight: '800', color: P.ink },
  trashPageSub: { fontSize: 12, color: P.faint, marginTop: 2, textAlign: 'center' },
  trashList: { flex: 1, paddingHorizontal: 14, paddingTop: 12 },
  trashEmptyText: { fontSize: 14, color: P.text3, textAlign: 'center', marginTop: 40 },
  trashFooter: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: P.border,
  },
  vaultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: P.border,
  },
  vaultTitle: { flex: 1, fontSize: 17, fontWeight: '800', color: P.ink, textAlign: 'center' },

  vaultList: { paddingHorizontal: 12, paddingTop: 10, paddingBottom: 16 },
  vaultFooter: {
    borderTopWidth: 1,
    borderTopColor: P.border,
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 12,
    backgroundColor: P.paper,
  },
  vaultEditRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 8 },
  vaultEditInput: {
    backgroundColor: P.input,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 15,
    color: P.ink,
    borderWidth: 1,
    borderColor: P.border,
    minHeight: 80,
    textAlignVertical: 'top',
  },
  trashBtnText: { fontSize: 17 },
  inviteCode: {
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: 6,
    color: P.ink,
    backgroundColor: P.surface,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: P.border,
  },
  inviteInput: {
    width: '100%',
    backgroundColor: P.input,
    borderRadius: 12,
    padding: 14,
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 4,
    color: P.ink,
    borderWidth: 1,
    borderColor: P.border,
    marginBottom: 12,
  },
  modalRow: { flexDirection: 'row', gap: 10, width: '100%' },
  modalBtn: {
    flex: 1,
    backgroundColor: P.ink,
    borderRadius: 12,
    padding: 13,
    alignItems: 'center',
  },
  modalBtnText: { color: P.paper, fontSize: 15, fontWeight: '700' },
  modalBtnGhost: { backgroundColor: 'transparent', borderWidth: 1, borderColor: P.border },
  modalBtnGhostText: { color: P.text3 },
  modalBtnDisabled: { opacity: 0.4 },
  modalLabel: { fontSize: 13, fontWeight: '700', color: P.text3, marginTop: 12, marginBottom: 6 },
  modalInputMulti: { minHeight: 90, textAlignVertical: 'top' },
  modalBtns: { flexDirection: 'row', gap: 10, marginTop: 16 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: P.border,
    backgroundColor: P.surface,
  },
  chipOn: { backgroundColor: P.ink, borderColor: P.ink },
  chipText: { fontSize: 14, color: P.ink },
  // list-only shopping: active lists + archive
  newListBtn: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: P.border,
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    backgroundColor: P.surface,
  },
  newListText: { fontSize: 15, fontWeight: '700', color: P.ink },
  shopListArchived: { backgroundColor: P.surface, borderColor: P.border },
  archRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 8 },
  archActions: { flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', marginTop: 6, gap: 14 },
  restoreBtn: { color: P.success, fontWeight: '700', fontSize: 14 },
  notFoundTag: {
    fontSize: 11,
    fontWeight: '700',
    color: P.dangerDeep,
    backgroundColor: P.dangerSoft,
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  shopMissBtn: { fontSize: 22 },
});
