name: EAS Submit iOS

on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'EAS Build ID to submit to TestFlight'
        required: true
        type: string

jobs:
  submit_ios:
    name: Submit app to TestFlight
    defaults:
      run:
        working_directory: ./apps/mobile
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Install EAS CLI
        run:
          command: npm install -g eas-cli
      - name: Submit to TestFlight
        run:
          command: eas submit --platform ios --id ${{ inputs.build_id }} --non-interactive
